license="All Rights Reserved"

[[mods]]
modId="terranova"
version="1.2.0"
displayName="Terra Nova"
logoFile="icon.png"
displayURL="https://github.com/kaylamay-darling/terranova"

authors="Kayla May (Code / Art), Kaya (Art)"

description='''
Enhances the Vanilla progression system, while adding world-building features. More to come...
'''

[[mixins]]
config = "terranova.mixins.json"

[[dependencies.terranova]]
modId="neoforge"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.terranova]]
modId="minecraft"
type="required"
versionRange="[26.1.2,)"
ordering="NONE"
side="BOTH"